export { NavBar } from './navBar/NavBar'
export { Hero } from './hero/Hero'
export { About } from './about/About'
export { Services } from './services/Services'
export { Footer } from './footer/Footer'
export { Contact } from './contactForm/Contact'
